name: pre-commit

on:
  pull_request:
  push:
    branches:
      - main
      - develop

env:
  APP_LOG_FILE_PATH: "logs/app.log"

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies from Pipfile
        run: |
          python -m pip install --upgrade pip
          pip install pipenv
          pipenv install --dev

      - name: Create logs folder
        run: |
          mkdir logs
          touch logs/app.log

      - name: Run pre-commit checks
        run: |
          pipenv run pre-commit run --all-files
