name: Unit Test Cases

on:
  pull_request:
  push:
    branches:
      - main
      - develop

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies from Pipfile
        run: |
          python -m pip install --upgrade pip
          pip install pipenv
          pipenv install --dev

      - name: Run unit test cases
        run: |
          pipenv run pytest .
